version: "3"
services:
  app:
    build:
      context: ../../
      dockerfile: ./Dockerfile

  selenium-hub:
    image: selenium/hub:4.1.0-20211209
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  
  firefox:
    image: selenium/node-firefox:4.1.0-20211209
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  e2e-tests:
    profiles: [ci]
    build:
      context: ../
      dockerfile: ./Dockerfile
    depends_on:
      - app
      - firefox
    environment:
      - CI=true
      - APP_URL=http://app:3000
      - CLOUD_URL=http://selenium-hub:4444
