name: QA Automation Coding Challenge workflow
run-name: ${{ github.actor }} pushed changes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
    
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test
  e2e-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: app-and-selenium-hub-configuration
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./e2e-tests/docker/docker-compose.yml"
          up-flags: "--build"
      - name: e2e-tests
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./e2e-tests/docker/docker-compose.yml"
          up-flags: "--attach e2e-tests --build --exit-code-from e2e-tests"